name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Docker hub login
      run: docker login --username ${{ secrets.DOCKERHUB_USER }} --password ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build with Maven
      run: mvn -B compile jib:build --file pom.xml

  prepare-nonprod-config-repo:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Create private key file ~/.ssh/id_rsa
      run: mkdir ~/.ssh && chmod 0700 ~/.ssh && printf -- "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Config git
      run: git config --global user.email "bitbucketpipeline@wherever.com" && git config --global user.name "Bitbucket Pipeline"
    - name: Load bitbucket.org host keys
      run: ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts && chmod 0600 ~/.ssh/known_hosts && ls -lR ~/.ssh
    - name: Check what git user is being used
      run: ssh -vv git@bitbucket.org
    - name: Checkout config repo
      run: rm -rf remote_repo && git clone git@bitbucket.org:lemonade-git/pincette-json-streams.config.tst.git remote_repo
    - name: Create the TAG file
      run: cd remote_repo && echo "${GITHUB_SHA}" > TAG && git add TAG && git commit --allow-empty -m "Update TAG with source repo commit hash" && git push
